import { useCallback, useMemo, useState } from "react";
import api from "../lib/api";
import { useApiQuery, useDebounced } from "../hooks/useApiQuery";
import { AlertList } from "../components/panels";
import { Card, Empty, ErrorState, FilterBar, Loading, SearchBox, Select, Tag } from "../components/ui";

const ZONES = ["Zone A", "Zone B", "Zone C"];

export default function Alerts({ refresh, onInspectEvent }) {
  const [q, setQ] = useState("");
  const dq = useDebounced(q, 250);
  const [status, setStatus] = useState("active");
  const [level, setLevel] = useState("all");
  const [zone, setZone] = useState("all");
  const [busyId, setBusyId] = useState(null);
  const [actionError, setActionError] = useState(null);
  const [feedback, setFeedback] = useState(null);

  const fetcher = useCallback(
    () => api.alerts({ status, level, zone, q: dq, limit: 300 }),
    [status, level, zone, dq],
  );
  const { data, error, loading, reload } = useApiQuery(fetcher, [status, level, zone, dq], { intervalMs: 5000 });

  const act = async (id, action) => {
    setBusyId(id);
    setActionError(null);
    setFeedback(null);
    try {
      const updated = await api.alertAct(id, action);
      setFeedback(`${id} → ${updated.status}`);
      await reload();
      refresh?.();
    } catch (e) {
      setActionError(e.message);
    } finally {
      setBusyId(null);
    }
  };

  const counts = useMemo(() => {
    const list = data || [];
    return list.reduce((acc, a) => ({ ...acc, [a.status]: (acc[a.status] || 0) + 1 }), {});
  }, [data]);

  return (
    <div className="stack">
      <Card
        title="Alert centre"
        subtitle="Alerts are generated by the backend when events are detected and when the lifecycle changes."
        badge={<Tag tone="info">{(data || []).length} shown</Tag>}
        actions={<button type="button" className="btn ghost" onClick={reload}>⟳ Refresh</button>}
      >
        <FilterBar active={Boolean(q || status !== "active" || level !== "all" || zone !== "all")}
                   onReset={() => { setQ(""); setStatus("active"); setLevel("all"); setZone("all"); }}>
          <SearchBox label="Search alerts" value={q} onChange={setQ} placeholder="title, message, alert id…" />
          <Select label="Status" value={status} onChange={setStatus} allLabel="Any status"
                  options={[{ value: "active", label: "Active" }, { value: "acknowledged", label: "Acknowledged" },
                            { value: "resolved", label: "Resolved" }]} />
          <Select label="Level" value={level} onChange={setLevel} allLabel="All levels"
                  options={["INFO", "WATCH", "WARNING", "CRITICAL"]} />
          <Select label="Zone" value={zone} onChange={setZone} options={ZONES} allLabel="All zones" />
        </FilterBar>

        <p className="muted small">
          {counts.active || 0} active · {counts.acknowledged || 0} acknowledged · {counts.resolved || 0} resolved
          (current filter). Acknowledging records that an operator has seen the alert; resolving closes it.
        </p>
        {feedback && <p className="inline-ok" role="status">{feedback}</p>}
        {actionError && <p className="inline-error" role="alert">{actionError}</p>}

        {loading && !data && <Loading label="Loading alerts…" />}
        {error && <ErrorState message={error} onRetry={reload} />}
        {data && (
          <AlertList alerts={data} busyId={busyId}
                     onAction={(id, action) => {
                       const alert = (data || []).find((a) => a.id === id);
                       if (action === "acknowledge" && alert?.disruption_id) {
                         onInspectEvent?.(alert.disruption_id);
                       }
                       return act(id, action);
                     }} />
        )}
      </Card>

      <Card title="Alert policy" subtitle="How CityPulse escalates">
        <ul className="why">
          <li><b>WATCH</b> — a possible multi-signal civic disruption has formed (≥3 signal types in one zone).</li>
          <li><b>WARNING</b> — the event is escalating; signal strength is still increasing.</li>
          <li><b>CRITICAL</b> — the event has reached its peak score.</li>
          <li><b>INFO</b> — lifecycle notices (recovery, resolution, operator actions).</li>
        </ul>
        <p className="muted small">
          Alerts are kept in backend memory for the lifetime of the process. They are not written to durable storage —
          restarting the backend clears the queue.
        </p>
      </Card>
    </div>
  );
}
